development:
  adapter: mysql2
  encoding: utf8
  database: roots_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: roots_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: roots_production
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
