# Copy this file to config/settings_private.yml then input all your settings
# here.
#
# For example, below you can access "ABC123" through PRIVATE['my_special_key']
#
development: &default
  my_special_key: "ABC123"

test:
  <<: *default

production:
  <<: *default
